on:
  release:
    types:
      - created

name: Release PDF

jobs:
  build:
    name: Compile and upload asciidoc to pdf
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Asciidoc PDF Compilation
        uses: docker://asciidoctor/docker-asciidoctor:latest
        with:
          entrypoint: asciidoctor-pdf
          args: -a icons=font -a source-highlighter=coderay paper/appendix/README.adoc

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./paper/appendix/README.pdf
          asset_name: appendix.pdf
          asset_content_type: application/pdf

